---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  pre_tasks:
    - name: "wait 120 seconds for target connection to become reachable/usable."
      wait_for_connection:

  roles:
    - run-docker-app    


