---
- name: configuration play 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  gather_facts: false
  tasks:

  - name: copy files
    copy:
      src: ./
      dest: tmp/
      
  - name: start nginx container
    shell: |
      cd tmp
      docker image ls
      docker compose up --build
      docker rmi $(docker images --filter "dangling=true" -q --no-trunc)

  - name: Ending the 1st play now
      meta: end_play    