version: '3.5'

services:
    circle-nodejs-app:
        build:
          context: ./node-app
        image: aminfourty7/test-nodejs:latest  
        container_name: circle-nodejs-app
        hostname: nodejs-app
        ports:
            - "3000:3000"
    circle-nginx:
        build:
          context: ./nginx
        image: aminfourty7/test-nginx:latest  
        container_name: circle-nginx
        hostname: nginx
        ports:
            - "80:80" 
        depends_on:
            - circle-nodejs-app