version: '3.5'

services:
    nodejs-app:
        build:
          context: ./node-app
        image: aminfourty7/nodejs-kubernetes:latest  
        container_name: nodejs-app
        hostname: nodejs-app
        ports:
            - "3000:3000"  
    nginx:
        build:
          context: ./nginx
        image: aminfourty7/nginx-kubernetes:latest  
        container_name: nginx
        hostname: nginx
        ports:
            - "80:80" 
        depends_on:
            - nodejs-app