---
- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  tasks:

  - name: copy files
    copy:
      src: ./
      dest: tmp/
  - name: start nginx container
  become: yes
  shell: |
    cd tmp
    docker image ls
    docker compose up
