version: 2.1

jobs:
  build-nodejsapp:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - restore_cache:
          keys: [nodejs-build]
      - run:
          name: Build nodeapp
          command: |
            cd node-app
            npm install
      - save_cache:
          paths: [node-app/node_modules]
          key: nodejs-build
  test-nodejsapp:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - restore_cache:
          keys: [nodejs-build]
      - run:
          name: Run nodeapp tests
          command: |
            cd node-app
            npm install
            npm run test
  scan-nodejsapp:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - restore_cache:
          keys: [nodejs-build]
      - run:
          name: Audit & Analyze Nodeapp
          command: |
            cd node-app
            npm install
            npm audit fix --audit-level=critical  
  build-nodeapp-dockerimages:
    docker:
      - image: cimg/go:1.13
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build nodeapp image
          command: |
            cd node-app
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
            docker build -t aminfourty7/nodejs-kubernetes:latest .
            docker push aminfourty7/nodejs-kubernetes:latest
  build-nginx-dockerimages:
    docker:
      - image: cimg/go:1.13
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build nginx image
          command: |
            cd nginx
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
            docker build -t aminfourty7/nginx-kubernetes:latest .
            docker push aminfourty7/nginx-kubernetes:latest
  get-instance-ip:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum install -y tar gzip
      - run:
          name: Add instance-end ip to ansible inventory
          command: |
            aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --filters "Name=tag:project,Values=docker-server" \
            --output text >> ~/project/.circleci/ansible/inventory
            cat ~/project/.circleci/ansible/inventory
      - persist_to_workspace:
          root: ~/
          paths:
            - project/.circleci/ansible/inventory
  run-containers:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["9f:7e:0b:c8:94:45:60:f3:7a:95:ef:73:ca:42:dd:62"]
      - run:
          name: install dependencies
          command: |
            yum install -y ansible tar gzip aws-cli
      - attach_workspace:
          at: ~/    
      - run:
          name: run containers
          command: |
            cd .circleci/ansible
            ansible-playbook -i inventory.txt run-docker-app.yaml                            
workflows:
  docker-deployment:
    jobs:
      - build-nodejsapp
      - test-nodejsapp:
          requires: [build-nodejsapp]
      - scan-nodejsapp:
          requires: [build-nodejsapp]
      - build-nodeapp-dockerimages:
          requires: [scan-nodejsapp]
      - build-nginx-dockerimages:
          requires: [scan-nodejsapp]    
      - get-instance-ip:
          requires: [test-nodejsapp, scan-nodejsapp]
      - run-containers:
          requires: [get-instance-ip]     
      #- configure-infrastructure:
      #    requires: [deploy-infrastructure]
      #- run-migrations:
      #    requires: [configure-infrastructure]
      #- deploy-frontend:
      #    requires: [run-migrations]
      #- deploy-backend:
      #    requires: [run-migrations]
      #- smoke-test:
      #    requires: [deploy-backend, deploy-frontend]
      #- cloudfront-update:
      #    requires: [smoke-test]
      #- cleanup:
      #    requires: [cloudfront-update]    