version: 2.1

jobs:
  build-nodejsapp:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - restore_cache:
          keys: [nodejs-build]
      - run:
          name: Build nodeapp
          command: |
            cd node-app
            npm install
      - save_cache:
          paths: [node-app/node_modules]
          key: nodejs-build
  test-nodejsapp:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - restore_cache:
          keys: [nodejs-build]
      - run:
          name: Run nodeapp tests
          command: |
            cd node-app
            npm install
            npm run test
  scan-nodejsapp:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - restore_cache:
          keys: [nodejs-build]
      - run:
          name: Audit & Analyze Nodeapp
          command: |
            cd node-app
            npm install
            npm audit fix --audit-level=critical         
workflows:
  blue-green-deployment:
    jobs:
      - build-nodejsapp
      - test-nodejsapp:
          requires: [build-nodejsapp]
      - scan-nodejsapp:
          requires: [build-nodejsapp]
      #- deploy-infrastructure:
      #    requires: [test-frontend, test-backend, scan-frontend, scan-backend]    
      #- configure-infrastructure:
      #    requires: [deploy-infrastructure]
      #- run-migrations:
      #    requires: [configure-infrastructure]
      #- deploy-frontend:
      #    requires: [run-migrations]
      #- deploy-backend:
      #    requires: [run-migrations]
      #- smoke-test:
      #    requires: [deploy-backend, deploy-frontend]
      #- cloudfront-update:
      #    requires: [smoke-test]
      #- cleanup:
      #    requires: [cloudfront-update]    